### ISSUE TITLE
Fix shadowed deepseq dependency

### ISSUE THREAD

**Issue by bigs** [mthom/shentong#3]
hello!

when compiling from source in a fresh sandox, i was greeted with the error:

```
Preprocessing executable 'shen' for shentong-0.2.0...

Shentong/Primitives.hs:11:8:
    Could not find module ‘Control.DeepSeq’
    It is a member of the hidden package ‘deepseq-1.3.0.2’.
    Perhaps you need to add ‘deepseq’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
shentong-0.2.0 failed during the building phase. The exception was:
ExitFailure 1
```

this is easily fixed by adding `, deepseq == 1.3.0.2` to the `build-depends` list in `shentong.cabal`. should i go ahead and post the commit? do you have a preference to locking in to a given version?

**Comment by mthom** [comment]
Oops, that's my fault. I've removed the DeepSeq import line in Primitives.hs and sandboxing should now work without the added dependency. Thanks for pointing this out.

**Comment by bigs** [comment]
no problem. just re-familiarizing myself with shen (my, how it's grown!) and digging into your implementation. eager to contribute. do you have any todos?

**Comment by mthom** [comment]
Yes, two major ones.

1) Haskell->Shen FFI. I'm looking at ways to dynamically load Haskell libraries into the REPL. This would involve loading the Haskell code at run time and using datatype generics to project the functions/values of the library modules into Shentong's Function/KLValue type. That may be the hard part. I'd also like the loader to generate Shen data types for use with the wrapped functions/values, but that's comparatively easy. Algebraic data types are trivially easy to represent in Shen's type system. The question of how to work around IO and ST worries me a lot more. The primitive types (Word8, Char, etc.) will also need some finesse. It seems the GHC module has all the code needed to do dynamic loading, but unfortunately the documentation is poor. As for datatype generics, I'd like to use Data.Data and Data.Typeable (Scrap Your Boilerplate). People say that GHC.Generics is faster, but I prefer Data.Data and Data.Typeable for their age.

2) Improving the backend. I posted in the Shen Google Groups forum about adding types to the Shen sources, which are now published (and themselves written in Shen). Shen is syntactically much closer to Haskell than it is to Scheme, which is what KLambda more closely resembles. If you look over the backend code, you'll see it's a direct port of the KLambda sources to Haskell, which carries severe readability and performance costs. My current thought is that if the Shen sources are concisely typed, I can programmatically generate a Haskell backend that will hopefully be as readable and performant as something a decent Haskell programmer would write by hand.

If there's anything you think could be added or improved, please let me know.
