### ISSUE TITLE
publish to Hackage?

### ISSUE THREAD

**Issue by juhp** [mthom/shentong#4]
Any plans to release/publish the package on Hackage?

**Comment by mthom** [comment]
That would make it easier to install. I'm a little wary of anything to do with Cabal, to be honest. Presently there are no plans.

**Comment by juhp** [comment]
I see.  Wary in what sense?  You already have a .cabal file, so all you would need to do is to upload it. :-)

**Comment by mthom** [comment]
Wary in the sense that cabal hell is a thing I don't entirely understand or want to be drawn into. :)
But yes, I'll take a look at posting the project to Hackage.

**Comment by juhp** [comment]
Great, thanks

I think Cabal hell is less of a problem for executables than for library stacks etc.

**Comment by mthom** [comment]
Okay, I successfully published Shentong to Hackage, but after updating my cabal it doesn't seem to be available for download! Does that take some time, or is something wrong?

**Comment by mthom** [comment]
Okay, I successfully published Shentong to Hackage and it now seems to be available for download. You will need GHC 8.0.1. Please let me know if it works and I'll close the issue.

**Comment by juhp** [comment]
Thank you very much

Shen is cool so it is nice to have it on Hackage

ps I noticed this while building:

```
Shentong/Backend/Prolog.hs:978:41: warning:
    Pattern match checker exceeded (2000000) iterations in
    a case alternative. (Use -fmax-pmcheck-iterations=n
    to set the maximun number of iterations to n)

Shentong/Backend/Prolog.hs:3035:42: warning:
    (ditto)
```
